services:
  - type: web
    name: audiomixmaster
    env: python
    buildCommand: ./build.sh
    startCommand: gunicorn --bind 0.0.0.0:$PORT --workers 1 --timeout 120 app:app
    region: oregon
    healthCheckPath: /
